### ISSUE TITLE
customer reports issue with pbi not displaying viz

### ISSUE THREAD

**Issue by DataBoyTX** [graphistry/graphbi#88]
Message from client: 

> We both (my student and myself)  use powerbi Desktop version. It ran this morning but since a while same error at both computers.
> 
> From time to time there’s a total stuck, saving the file and restart of PBI works so far
> 
> If we switch to browser (by “open in new tab”), everything is fine.
> 
> As we need to work on the data model, we cannot move to PowerBI service, otherwise we have to switch from Desktop to Browser and vice versa

![pbi_issue](https://user-images.githubusercontent.com/11410059/215691424-068751e9-1044-4938-9bd5-427482ff3091.png)

also reporting back: 

> Dockers on this server have been up for 5 days and are all healthy

Since the viz is displaying fine on the server, leads me to believe that the issue is client-side, somehow in the powerbi app, maybe it's losing the connection, out of memory after several reloads, etc..  not sure how to debug the pbi viz on the client.

**Comment by DataBoyTX** [comment]
Client reported back that the issue is no longer happening and he wasn't sure what changed.  He said that there could have been some changes to their VPN configuration, but didn't provide any additional details.  They will report back if the issue occurs again.

**Comment by lmeyerov** [comment]
I wonder if should do some sort of connection health monitor pop-up

The viz gets into a reconnecting message when the websocket closes

But the powerbi component wraps above that, and the problem is the upload step (I think)

**Comment by DataBoyTX** [comment]
I've always wondered how to debug these client side issues. I mean, I think I've seen you pop into the browser dev tools and look at stuff, but I don't really know how to do that.  So, making this easy or a red/green light that alternates colors when the state is bad and if you click on it then the details of the issue would be shown I think would be helpful. I also imagine some users wont have access to log into the console to look at logs, so any additional information we could give them that they could share with their admins or us would be welcomed.  

I've felt like I was in the dark a few times when some status messages would flash by in the top right of the screen and then there would be a timeout error or something like that.  Any additional logging of these things would be great for troubleshooting.
